# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  VULKAN_SDK_VERSION: 1.4.328.1
  VULKAN_SDK: "C:\\VulkanSDK\\1.4.328.1"

  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./VulkanWin32.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: UnitTest_R

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create Files
      run: mkdir C:/VulkanSDK
    
    - name: Cache Vulkan SDK
      id: cache-vulkan-sdk
      uses: actions/cache@v3
      with:
        path: C:/VulkanSDK/${{ env.VULKAN_SDK_VERSION }}
        key: vulkan-sdk-${{ runner.os }}-${{ env.VULKAN_SDK_VERSION }}

    - name: Setup Vulkan
      if: runner.os == 'Windows' && steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      run: |
        $vulkanInstaller = "vulkansdk-windows-X64-$env:VULKAN_SDK_VERSION.exe"
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$env:VULKAN_SDK_VERSION/windows/${vulkanInstaller}" -OutFile $vulkanInstaller
        Start-Process -FilePath $vulkanInstaller -Wait -ArgumentList @("--accept-licenses", "--default-answer", "--confirm-command", "install")
        Remove-Item -Path $vulkanInstaller

    - name: Fix environment variables
      run: |
          "VULKAN_SDK=$env:VULKAN_SDK" >> $env:GITHUB_ENV
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          refreshenv
          echo "VULKAN_SDK is $env:VULKAN_SDK"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run unit test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./x64/${{env.BUILD_CONFIGURATION}}/VulkanWin32.exe --test
